version: '3.8'

services:
  server:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8005
    ports:
      - "8005:8005"
    volumes:
      - .:/app
    restart: unless-stopped

  consumer:
    build: .
    command: python consumer.py
    volumes:
      - .:/app
    restart: unless-stopped
