version: '3.8'

services:
  server:
    build: .
    ports:
      - "8005:8005"
    volumes:
      - .:/app
    restart: unless-stopped

  consumer:
    build: .
    command: python consumer.py
    volumes:
      - .:/app
    restart: unless-stopped
