"""Add subject column to olymps

Revision ID: bf46aa083683
Revises: 
Create Date: 2025-07-30 20:08:13.672712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf46aa083683'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_olymp_results_id'), table_name='olymp_results')
    op.drop_index(op.f('ix_olymp_results_olymp_id'), table_name='olymp_results')
    op.drop_table('olymp_results')
    op.drop_index(op.f('ix_olymps_id'), table_name='olymps')
    op.drop_table('olymps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olymps',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('olymps_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='olymps_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_olymps_id'), 'olymps', ['id'], unique=False)
    op.create_table('olymp_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('olymp_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['olymp_id'], ['olymps.id'], name=op.f('olymp_results_olymp_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('olymp_results_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('olymp_results_pkey'))
    )
    op.create_index(op.f('ix_olymp_results_olymp_id'), 'olymp_results', ['olymp_id'], unique=False)
    op.create_index(op.f('ix_olymp_results_id'), 'olymp_results', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('who_interested', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
