"""Add gender to user

Revision ID: fab10dd7957d
Revises: 7fea904c5ca4
Create Date: 2025-08-07 12:18:31.630487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab10dd7957d'
down_revision: Union[str, Sequence[str], None] = '7fea904c5ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_olymps_id'), table_name='olymps')
    op.drop_table('olymps')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olymps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_tg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_displayed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_tg_id'], ['users.tg_id'], name=op.f('olymps_user_tg_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('olymps_pkey'))
    )
    op.create_index(op.f('ix_olymps_id'), 'olymps', ['id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_user_tg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_user_tg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_like', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_readed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_user_tg_id'], ['users.tg_id'], name=op.f('likes_from_user_tg_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_tg_id'], ['users.tg_id'], name=op.f('likes_to_user_tg_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('likes_pkey'))
    )
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('who_interested', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('face_photo_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
